spring:
  datasource:
    url: jdbc:mysql://localhost/avoindata?autoReconnect=true&rewriteBatchedStatements=true&cachePrepStmts=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

server:
  port: 8081

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


graphql:
  servlet:
    mapping: /graphql
    enabled: true

cache:
  expiryInSeconds: 15
  maxCacheSize: 5
