spring:
  datasource:
    url: jdbc:mysql://localhost/avoindata?autoReconnect=true&rewriteBatchedStatements=true&cachePrepStmts=true&useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate.dialect: 'org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect'
server:
  port: 8081

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


graphql:
  servlet:
    mapping: /graphql
    enabled: true

graphiql:
  pageTitle: Local GraphiQL

cache:
  expiryInSeconds: 15
  maxCacheSize: 5
