spring:
  datasource:
    url: jdbc:mysql:aws://localhost/avoindata_test?autoReconnect=true&rewriteBatchedStatements=true&cachePrepStmts=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: 
  jpa:
    properties:
      hibernate.dialect: 'org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect'
      javax:
        persistence:
          query:
            timeout: 7500
    open-in-view: false
  mvc:
    async:
      request-timeout: 10000
server:
  port: 8081

logging:
  level:
    root: INFO
    #    graphql.GraphQL: DEBUG
    #    org.springframework.web.servlet.DispatcherServlet: DEBUG
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  health:
    diskspace:
      enabled: false
    db:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always

graphql:
  servlet:
    mapping: /graphql
    enabled: true

graphiql:
  pageTitle: Local GraphiQL

cache:
  expiryInSeconds: 15
  maxCacheSize: 5

digitraffic:
  max-returned-rows: 5000
  fields-that-can-be-queried-twice:
    - "station"
  hidden-fields:
    - "Train.trainTypeId"
    - "Train.operatorShortCode"
    - "Train.trainCategoryId"
    - "TimeTableRow.id"
    - "TimeTableRow.trainNumber"
    - "TimeTableRow.departureDate"
    - "TimeTableRow.stationShortCode"
    - "TimeTableRow.stationUICCode"
    - "TimeTableRow.countryCode"
    - "Cause.timeTableRowId"
    - "Cause.trainNumber"
    - "Cause.departureDate"
    - "Cause.categoryCodeOid"
    - "Cause.detailedCategoryCodeOid"
    - "Cause.thirdCategoryCodeOid"
    - "Cause.id"
    - "CategoryCode.oid"
    - "DetailedCategoryCode.oid"
    - "DetailedCategoryCode.categoryCodeOid"
    - "ThirdCategoryCode.oid"
    - "ThirdCategoryCode.detailedCategoryCodeOid"
    - "TrainLocation.departureDate"
    - "TrainLocation.trainNumber"
    - "Composition.trainNumber"
    - "Composition.departureDate"
    - "Composition.operatorShortCode"
    - "Composition.operatorUicCode"
    - "Composition.trainCategoryId"
    - "Composition.trainTypeId"
    - "JourneySection.id"
    - "JourneySection.trainNumber"
    - "JourneySection.departureDate"
    - "JourneySection.beginTimeTableRowId"
    - "JourneySection.endTimeTableRowId"
    - "Locomotive.id"
    - "Locomotive.journeysectionId"
    - "Wagon.id"
    - "Wagon.journeysectionId"
    - "Station.id"
    - "TrainCategory.id"
    - "TrainType.id"
    - "TrainType.trainCategoryId"
    - "TrainTrackingMessage.trainNumber"
    - "TrainTrackingMessage.departureDate"
    - "TrainTrackingMessage.stationShortCode"
    - "TrainTrackingMessage.previousStationShortCode"
    - "TrainTrackingMessage.nextStationShortCode"
    - "TrackSectionCode.id"
    - "TrackRange.trackSectionId"
    - "RoutesetMessage.trainNumber"
    - "RoutesetMessage.departureDate"
    - "Routesection.stationCode"
