package fi.digitraffic.graphql.rail.webmvc;

import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;

import java.time.LocalDate;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.web.servlet.ResultActions;

import fi.digitraffic.graphql.rail.entities.Train;
import fi.digitraffic.graphql.rail.repositories.TrainRepository;

/**
 * Integration tests for the 'contains' operator in GraphQL where clauses.
 * Verifies that EXISTS subqueries generated by JpqlWhereBuilder work correctly
 * against the database through the full GraphQL stack.
 */
public class ContainsFilterQueriesTest extends BaseWebMVCTest {

    private static final LocalDate DATE = LocalDate.of(2024, 6, 1);

    @Autowired
    private TrainRepository trainRepository;

    @Test
    public void containsWithStationViaRelation() throws Exception {
        // All base trains have stations HKI, PSL, TPE, JY, OL
        factoryService.getTrainFactory().createBaseTrain(1, DATE);
        factoryService.getTrainFactory().createBaseTrain(2, DATE);

        // Filter trains that stop at a STATION type — should match both
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    station: { type: { equals: "STATION" } }
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate.length()").value(2));
    }

    @Test
    public void containsWithNoMatch() throws Exception {
        factoryService.getTrainFactory().createBaseTrain(1, DATE);

        // Filter for a station type that doesn't exist in any train's timetable
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    station: { type: { equals: "TURNOUT_IN_THE_OPEN_LINE" } }
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate").isEmpty());
    }

    @Test
    public void containsWithAndConditions() throws Exception {
        // Base train has DEPARTURE from HKI and ARRIVAL+DEPARTURE at PSL, TPE, JY, and ARRIVAL at OL
        factoryService.getTrainFactory().createBaseTrain(1, DATE);

        // Find trains with a DEPARTURE row at a station of type STATION — should match
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    and: [
                                        { station: { type: { equals: "STATION" } } },
                                        { type: { equals: "DEPARTURE" } }
                                    ]
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate.length()").value(1));
        result.andExpect(jsonPath("$.data.trainsByDepartureDate[0].trainNumber").value(1));
    }

    @Test
    public void containsWithAndConditionsNoMatch() throws Exception {
        // Base train: no cancelled time table rows
        factoryService.getTrainFactory().createBaseTrain(1, DATE);

        // Find trains with a DEPARTURE that is cancelled — should not match
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    and: [
                                        { type: { equals: "DEPARTURE" } },
                                        { cancelled: { equals: true } }
                                    ]
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate").isEmpty());
    }

    @Test
    public void containsCombinedWithTopLevelWhere() throws Exception {
        final Train train1 = factoryService.getTrainFactory().createBaseTrain(1, DATE).getFirst();
        final Train train2 = factoryService.getTrainFactory().createBaseTrain(2, DATE).getFirst();

        train1.timetableType = Train.TimetableType.ADHOC;
        train2.timetableType = Train.TimetableType.REGULAR;
        trainRepository.saveAll(List.of(train1, train2));

        // Both trains stop at STATION type stations, but only train1 is ADHOC
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timetableType: { equals: "ADHOC" },
                            timeTableRows: {
                                contains: {
                                    station: { type: { equals: "STATION" } }
                                }
                            }
                        }) {
                        trainNumber
                        timetableType
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate.length()").value(1));
        result.andExpect(jsonPath("$.data.trainsByDepartureDate[0].trainNumber").value(1));
    }

    @Test
    public void containsSelectivelyFiltersTrains() throws Exception {
        factoryService.getTrainFactory().createBaseTrain(1, DATE);
        factoryService.getTrainFactory().createBaseTrain(2, DATE);

        // Filter for trains with an ARRIVAL type row — both should match
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    type: { equals: "ARRIVAL" }
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate.length()").value(2));
    }

    @Test
    public void containsWithCancelledFilter() throws Exception {
        factoryService.getTrainFactory().createBaseTrain(1, DATE);

        // Filter trains whose timeTableRows contain a cancelled row — none are cancelled by default
        final ResultActions result = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    cancelled: { equals: true }
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result.andExpect(jsonPath("$.data.trainsByDepartureDate").isEmpty());

        // Filter for non-cancelled rows — should match
        final ResultActions result2 = this.query("""
                {
                    trainsByDepartureDate(departureDate: "2024-06-01",
                        where: {
                            timeTableRows: {
                                contains: {
                                    cancelled: { equals: false }
                                }
                            }
                        }) {
                        trainNumber
                    }
                }""");

        result2.andExpect(jsonPath("$.data.trainsByDepartureDate.length()").value(1));
    }
}
