name: Build
on: [push]
jobs:
  build:
    if: github.repository != 'tmfg/digitraffic-rail-graphql'
    runs-on: ubuntu-22.04
    services:
      dt-rail-mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD:
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn -f pom.xml install -e -U -DskipTests=true -Ddependency-check.skip=true
      - name: Checkout rail
        uses: actions/checkout@v4
        with:
          repository: tmfg/digitraffic-rail
          path: digitraffic-rail
      - name: Setup database
        working-directory: digitraffic-rail/dbrail
        run: docker compose up
      - name: Get database IP
        run: echo "db_addr=$(docker inspect dbrail_db_1 -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}')" >> $GITHUB_ENV
      - name: Run tests
        run: mvn -f pom.xml test -spring.datasource.url=jdbc:mysql://${{ env.db_addr }}/avoindata_test?autoReconnect=true&rewriteBatchedStatements=true&cachePrepStmts=true&useTimezone=true&serverTimezone=UTC
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: jUnit tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Rail GraphQL build
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
