name: Build
on: [push]
jobs:
  build:
    if: github.repository != 'tmfg/digitraffic-rail-graphql'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Compile
        run: mvn -f pom.xml install -e -U -DskipTests=true -Ddependency-check.skip=true
      - name: Run tests
        run: mvn -f pom.xml test
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Rail GraphQL build
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
