name: Install
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'beta'
      ref:
        description: 'Branch/tag/SHA of digitraffic-rail-graphql-private'
        required: true
        default: 'master'
      diff-only:
        description: "Only run diff"
        required: true
        type: boolean
        default: false
      config-repo-branch:
        description: 'Config repo branch'
        default: master
        required: true
        type: string
jobs:
  install:
    if: github.repository != 'tmfg/digitraffic-rail-graphql'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Log workflow inputs and environment
        run: |
          echo "## Workflow Inputs" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| actor | ${{ github.actor }} |" >> $GITHUB_STEP_SUMMARY
          echo "| env | ${{ github.event.inputs.env }} |" >> $GITHUB_STEP_SUMMARY
          echo "| ref | ${{ github.event.inputs.ref }} |" >> $GITHUB_STEP_SUMMARY
          echo "| diff-only | ${{ github.event.inputs.diff-only }} |" >> $GITHUB_STEP_SUMMARY
          echo "| config-repo-branch | ${{ github.event.inputs.config-repo-branch }} |" >> $GITHUB_STEP_SUMMARY
          # echo "| db-install | ${{ github.event.inputs.db-install }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Checkout CI-repo
        uses: actions/checkout@v7
        with:
          repository: ${{ secrets.CONFIG_REPO_NAME }}
          ssh-key: ${{ secrets.CONFIG_REPO_SSH_KEY }}
          ref: ${{ inputs.config-repo-branch }}
          path: digitraffic-ci
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: corretto
          cache: maven
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: gh-actions-build-rail-graphql-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build
        run: |
          mvn -f pom.xml install -e -U -DskipTests=true -Ddependency-check.skip=true

          cp target/rail-graphql-0.0.1-SNAPSHOT.jar digitraffic-ci/aws/rail-graphql.jar
          cd digitraffic-ci/aws
          
          docker buildx build \
            --no-cache \
            --build-arg APP_FILE=rail-graphql.jar \
            --build-arg PROPERTY_FILE=conf/rail/graphql-${{ github.event.inputs.env }}.properties \
            --build-arg LOGCONF_FILE=conf/rail/graphql-logback.xml \
            --platform linux/arm64 \
            --output type=docker \
            --tag ${{ secrets.ECR_URL }}/dt-rail-graphql-repository:${{ github.sha }}-${{ github.run_id }} \
            --pull=true \
            --file=docker/Dockerfile-rail-graphql .
          
          docker push ${{ secrets.ECR_URL }}/dt-rail-graphql-repository:${{ github.sha }}-${{ github.run_id }}
      - name: Put backend tag in Parameter Store
        run: |
          aws ssm put-parameter \
            --name "/rail/graphql/image-tag" \
            --value "${{ github.sha }}-${{ github.run_id }}" \
            --type "String" \
            --overwrite
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Generate graphql SBOM
        run: |
          mvn -DoutputName=graphql-sbom cyclonedx:makeBom
      - name: Upload graphql SBOM
        uses: actions/upload-artifact@v7
        with:
          name: graphql-sbom.json
          path: target/graphql-sbom.json

  deploy:
    if: ${{ always() && github.repository != 'tmfg/digitraffic-rail-graphql' && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    environment: ${{ github.event.inputs.env }}
    needs: install
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout CI-repo
        uses: actions/checkout@v6
        with:
          repository: ${{ secrets.CONFIG_REPO_NAME }}
          ssh-key: ${{ secrets.CONFIG_REPO_SSH_KEY }}
          ref: ${{ inputs.config-repo-branch }}
          path: digitraffic-ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: gh-actions-install-rail-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Build CI/CDK Infra project
        working-directory: digitraffic-ci/aws/cdk/infra
        run: |
          pnpm install
          pnpm build:ci

      - name: Diff and deploy
        env:
          DEPLOY_ALL_CHANGES: true
          DIFF_ONLY: ${{ github.event.inputs['diff-only'] }}
          # the value of AWS_PROFILE is only used by the stack code, local AWS profile configurations are not being set up
          AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
          STACK_NAME: Graphql${{ github.event.inputs['env'] == 'prod' && 'Prod' || 'Test' }}
        working-directory: digitraffic-ci/aws/cdk/infra/scripts
        run: |
          pnpm install
          pnpm build
          pnpm run start:diff-and-deploy $STACK_NAME      

      - name: Download graphql SBOM
        uses: actions/download-artifact@v8
        with:
          name: graphql-sbom.json

      - name: Read SBOM config
        id: sbom-config
        run: |
          echo "config<<EOF" >> $GITHUB_OUTPUT
          cat digitraffic-ci/aws/sbom/rail.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "common<<EOF" >> $GITHUB_OUTPUT
          cat digitraffic-ci/aws/sbom/config.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT                  

      - name: Configure AWS credentials for SBOM install
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ fromJson(steps.sbom-config.outputs.common).sbomUploadRoleArn }}
          role-session-name: gh-actions-upload-sbom-rail-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload SBOM files
        run: |
          aws s3 cp graphql-sbom.json s3://${{ fromJson(steps.sbom-config.outputs.common).bucketArn }}/${{ fromJson(steps.sbom-config.outputs.config)[github.event.inputs.env]['graphql'] }}/${{ github.run_id }}-${{ github.sha }}.json