name: "Mirror repo to public"
on:
  push:
    branches:
      - master
jobs:
  mirror-action:
    if: github.repository != 'tmfg/digitraffic-rail-graphql'
    runs-on: ubuntu-24.04
    steps:
      - name: mirror
        uses: tmfg/digitraffic-actions@mirror/v2
        with:
          mirror-repo: git@github.com:tmfg/digitraffic-rail-graphql.git
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
